services:
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: airguardian_user
            POSTGRES_PASSWORD: Hive_maoliiny_2025
            POSTGRES_DB: airguardian
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
